modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT https://github.com/BuiltBrokenModding/SBM-cardboardBoxes/blob/1.20.4/LICENSE"
issueTrackerURL = "https://github.com/BuiltBrokenModding/SBM-cardboardBoxes/issues"

[[mods]]
	modId = "cardboardboxes"
	version = "${file.jarVersion}"
	displayName = "[SBM] Cardboard Boxes"
	displayURL = "https://minecraft.curseforge.com/projects/sbm-cardboardboxes/"
	authors = "BuiltBrokenModding"
	description = '''Simplistic storage for moving block entities while maintaining inventories, and settings.'''

[[dependencies.cardboardboxes]]
	modId = "neoforge"
	mandatory = true
	versionRange = "[20.3,)"
	ordering = "NONE"
	side = "BOTH"

[[dependencies.cardboardboxes]]
	modId = "minecraft"
	mandatory = true
	versionRange = "[1.20.3,1.21)"
	ordering = "NONE"
	side = "BOTH"