modLoader = "javafml"
loaderVersion = "[41,)"
license = "MIT"
issueTrackerURL = "https://github.com/BuiltBrokenModding/SBM-cardboardBoxes/issues"

[[mods]]
	modId = "cardboardboxes"
	version = "${file.jarVersion}"
	displayName = "[SBM] Cardboard Boxes"
	displayURL = "https://minecraft.curseforge.com/projects/sbm-cardboardboxes/"
	authors = "BuiltBrokenModding"
	description = '''Simplistic storage for moving tiles while maintaining inventories, and settings.'''

[[dependencies.cardboardboxes]]
	modId = "forge"
	mandatory = true
	versionRange = "[41,)"
	ordering = "NONE"
	side = "BOTH"

[[dependencies.cardboardboxes]]
	modId = "minecraft"
	mandatory = true
	versionRange = "[1.19,1.20)"
	ordering = "NONE"
	side = "BOTH"